# Generated by Django 3.1.2 on 2020-12-21 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_repo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissions',
            old_name='type',
            new_name='perm',
        ),
    ]
