# Generated by Django 3.1.2 on 2020-12-21 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import image_repo.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image_repo', '0002_auto_20201221_0421'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to=image_repo.models.upload_to)),
                ('image_type', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_repo.imagedetails')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='image_repo.permissions')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageRepository',
        ),
    ]
