# Generated by Django 3.1.2 on 2020-12-21 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import image_repo.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image_repo', '0003_auto_20201221_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='image_repo.permissions')),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to=image_repo.models.upload_to)),
                ('image_type', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_repo.repository')),
            ],
        ),
        migrations.RemoveField(
            model_name='images',
            name='details',
        ),
        migrations.RemoveField(
            model_name='images',
            name='permission',
        ),
        migrations.DeleteModel(
            name='ImageDetails',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
