# Generated by Django 3.1.2 on 2020-12-21 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_repo', '0004_auto_20201221_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repositoryimages',
            old_name='image_url',
            new_name='image',
        ),
    ]
