# Generated by Django 3.1.2 on 2020-12-21 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_repo', '0005_auto_20201221_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryimages',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository', to='image_repo.repository'),
        ),
    ]
